/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.application;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author chris
 */
public class cashFrame extends javax.swing.JFrame {
    tesframe itemframe = new tesframe();
    tokenFrame tokenframe = new tokenFrame();
    pulsaFrame pulsaframe = new pulsaFrame();
    
//    static boolean pulsacheck = false;
    
    //value dari frame lain    
    float totalHargaPulsa = pulsaframe.getTotalHarga();
    float totalHargaBarang = itemframe.getTotalHarga();
    float totalHargaToken = tokenframe.getTotalHarga();
    
    //value dari cashframe
    static float dibayarCashFrame;
    static float kembalianCashFrame;
    
    //cashFrame yang dibuka dari pulsa
    private static boolean cashFramePulsaCheck = false;
    
    //cashFrame yang dibuka dari token
    private static boolean cashFrameTokenCheck = false;
    
    //cashFrame yang dibuka dari tesframe(item)
    private static boolean cashFrameItemCheck = false;
    
    /**
     * Creates new form cashFrame
     */
    public cashFrame() {
        initComponents();

        //check dari mana cashFrame dibuka
        while(true){
            if(pulsaFrame.check()){
                System.out.println(pulsaFrame.getNomorKartu());
                
                //kalo kebuka cashFramePulsaCheck berubah jadi true
                cashFramePulsaCheck = true;
                
                JTextField pulsa = new JTextField(20);
                pulsa.setLocation(271,104);  //104
                pulsa.setSize(170, 26);
                pulsa.setEditable(false);
                pulsa.setText(String.format("%,d", (int)totalHargaPulsa));
                jPanel1.add(pulsa);
                System.out.println("textfield pulsa");
                break;
            }
            else if(tesframe.check()){
                
                //kalo kebuka cashFrameItemCheck berubah jadi true
                cashFrameItemCheck = true;
                
                JTextField barang = new JTextField(20);
                barang.setLocation(271,104);  //104
                barang.setSize(170, 26);
                barang.setEditable(false);
                jPanel1.add(barang);
                barang.setText(String.format("%,d", (int)totalHargaBarang));
                System.out.println("textfield barang");
                break;
            }
            else if(tokenFrame.check()){
                
                //kalo kebuka cashFrameTokenCheck berubah jadi true
                cashFrameTokenCheck = true;
                
                JTextField token = new JTextField(20);
                token.setLocation(271,104);  //104
                token.setSize(170, 26);
                token.setEditable(false);
                jPanel1.add(token);
                token.setText(String.format("%,d", (int)totalHargaToken));
                System.out.println("textfield token");
                break;
            }
        }     
    }
    
    public static float getDibayarCashFrame(){
        return dibayarCashFrame;
    }
    
    public static float getKembalianCashFrame(){
        return kembalianCashFrame;
    }
    
    public static boolean cashFramePulsaisActive(){
        return cashFramePulsaCheck;
    }
    
    public static boolean cashFrameTokenisActive(){
        return cashFrameTokenCheck;
    }
    
    public static boolean cashFrameItemisActive(){
        return cashFrameItemCheck;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dibayarTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kembalianTextField = new javax.swing.JTextField();
        invisibleDibayarTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(26, 69, 224));

        jLabel1.setFont(new java.awt.Font("Montserrat Thin", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jumlah yang dibayar");

        dibayarTextField.setBackground(new java.awt.Color(255, 255, 255));
        dibayarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dibayarTextFieldActionPerformed(evt);
            }
        });
        dibayarTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dibayarTextFieldKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Montserrat Thin", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Belanjaan");

        jLabel3.setFont(new java.awt.Font("Montserrat Thin", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kembalian");

        kembalianTextField.setEditable(false);
        kembalianTextField.setBackground(new java.awt.Color(255, 255, 255));

        invisibleDibayarTextField.setEditable(false);
        invisibleDibayarTextField.setBackground(new java.awt.Color(26, 69, 224));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/application/115 asparagus.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dibayarTextField)
                    .addComponent(kembalianTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(invisibleDibayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dibayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembalianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(91, 91, 91)
                .addComponent(invisibleDibayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        invisibleDibayarTextField.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dibayarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dibayarTextFieldActionPerformed
        
        String pattern = "###,###,###";
        DecimalFormat decimalFormat = new DecimalFormat(pattern);
        
        if(pulsaFrame.check()){
            //pulsa
            float totalBelanja = totalHargaPulsa;
            System.out.println(totalBelanja);
            float dibayar = Float.valueOf(invisibleDibayarTextField.getText());
            dibayarCashFrame = dibayar;
            float kembalian = dibayar - totalBelanja;
            kembalianCashFrame = kembalian;
            
            String format = decimalFormat.format(kembalian);
            kembalianTextField.setText(format);
            pulsaFrame.uploadToDB();
        }
        else if(tesframe.check()){
            // barang/item
            float totalBelanja = totalHargaBarang;
            float dibayar = Float.valueOf(invisibleDibayarTextField.getText());
            dibayarCashFrame = dibayar;
            float kembalian = dibayar - totalBelanja;
            kembalianCashFrame = kembalian;
         
            String format = decimalFormat.format(kembalian);
            kembalianTextField.setText(format);
            if(getDibayarCashFrame() < itemframe.getTotalHarga()){
                kembalianTextField.setText(null);
            }
            tesframe.uploadToDB();
        }
        else if(tokenFrame.check()){
            //token
            float totalBelanja = totalHargaToken;
            float dibayar = Float.valueOf(invisibleDibayarTextField.getText());
            dibayarCashFrame = dibayar;
            float kembalian = dibayar - totalBelanja;
            kembalianCashFrame = kembalian;
            
            String format = decimalFormat.format(kembalian);
            kembalianTextField.setText(format);
            String Token = tokenFrame.tokenGenerator(20);
            String formattedToken = tokenFrame.TokenFormatter(Token);
            JOptionPane.showMessageDialog(null, "Pembayaran Berhasil!\nToken: "+formattedToken, "Success!", JOptionPane.INFORMATION_MESSAGE);
            tokenFrame.uploadToDB();
            this.dispose();
        }
    }//GEN-LAST:event_dibayarTextFieldActionPerformed

    private void dibayarTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dibayarTextFieldKeyReleased
        String dibayarString = dibayarTextField.getText();
        dibayarString = dibayarString.replace(",", "");
        
        float tempDibayar = Float.parseFloat(dibayarString);
        int dibayarInput = Integer.valueOf(dibayarString);
        
        invisibleDibayarTextField.setText(Float.toString(tempDibayar));
        
        dibayarTextField.setText(String.format("%,d", dibayarInput));
    }//GEN-LAST:event_dibayarTextFieldKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //reset totalHargaPulsa, finalTotalBelanja, dan totalHargaToken menjadi 0 ketika window ini di tutup
        totalHargaPulsa = 0;
        totalHargaBarang = 0;
        totalHargaToken = 0;
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dibayarTextField;
    private javax.swing.JTextField invisibleDibayarTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kembalianTextField;
    // End of variables declaration//GEN-END:variables
}
