/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.application;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author chris
 */
public class debitFrame extends javax.swing.JFrame {
    tesframe itemframe = new tesframe();
    tokenFrame tokenframe = new tokenFrame();
    pulsaFrame pulsaframe = new pulsaFrame();
    
    float totalHargaPulsa = pulsaframe.getTotalHarga();
    float totalHargaBarang = itemframe.getTotalHarga();
    float totalHargaToken = tokenframe.getTotalHarga();
    
    //debitFrame yang dibuka dari pulsa
    private static boolean debitFramePulsaCheck = false;
    
    //debitFrame yang dibuka dari token
    private static boolean debitFrameTokenCheck = false;
    
    //debitFrame yang dibuka dari tesframe(item)
    private static boolean debitFrameItemCheck = false;
    
    //nyimpan kembalian
    static float kembalianDebitFrame;
    static float currBalance;
    /**
     * Creates new form debitFrame
     */
    public debitFrame() {
        initComponents();
        
        //check dari mana debitFrame dibuka
        while(true){
            if(pulsaFrame.check()){
                System.out.println(pulsaFrame.getNomorKartu());
                
                //kalo kebuka debitFramePulsaCheck berubah jadi true
                debitFramePulsaCheck = true;
                
                JTextField pulsa = new JTextField(20);
                pulsa.setLocation(272,125);  
                pulsa.setSize(315, 26);
                pulsa.setEditable(false);
                pulsa.setText(String.format("%,d", (int)totalHargaPulsa));
                jPanel1.add(pulsa);
                System.out.println("textfield pulsa");
                break;
            }
            else if(tesframe.check()){
                
                //kalo kebuka debitFrameItemCheck berubah jadi true
                debitFrameItemCheck = true;
                
                JTextField barang = new JTextField(20);
                barang.setLocation(272,125);  
                barang.setSize(315, 26);
                barang.setEditable(false);
                jPanel1.add(barang);
                barang.setText(String.format("%,d", (int)totalHargaBarang));
                System.out.println("textfield barang");
                break;
            }
            else if(tokenFrame.check()){
                
                //kalo kebuka debitFrameTokenCheck berubah jadi true
                debitFrameTokenCheck = true;
                
                JTextField token = new JTextField(20);
                token.setLocation(272,125);  
                token.setSize(315, 26);
                token.setEditable(false);
                jPanel1.add(token);
                token.setText(String.format("%,d", (int)totalHargaToken));
                System.out.println("textfield token");
                break;
            }
        }     
    }
    
    public static boolean debitFramePulsaisActive(){
        return debitFramePulsaCheck;
    }
    
    public static boolean debitFrameTokenisActive(){
        return debitFrameTokenCheck;
    }
    
    public static boolean debitFrameItemisActive(){
        return debitFrameItemCheck;
    }
    
    public static float getKembalianDebitFrame(){
        return kembalianDebitFrame;
    }
    
    public static float getCurrentCardBalance(){
        return currBalance;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomorDebit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        submitBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(26, 69, 224));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Montserrat Thin", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Belanjaan");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/application/115 asparagus.png"))); // NOI18N

        nomorDebit.setBackground(new java.awt.Color(255, 255, 255));
        nomorDebit.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Montserrat Thin", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nomor Debit");

        submitBTN.setBackground(new java.awt.Color(255, 255, 255));
        submitBTN.setForeground(new java.awt.Color(0, 0, 0));
        submitBTN.setText("Submit");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Montserrat Thin", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bank");

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCA", "BRI", "Mandiri", "BNI", "CIMB", "Danamon", "Permata Bank" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(submitBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nomorDebit, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomorDebit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitBTN)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        String cardTxt = nomorDebit.getText();
        String cardNum = debitCards.getCardNumber();
        float cardBalance;
        
        if(cardTxt.isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukkan nomor kartu debit anda terlebih dahulu!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
       
        if(pulsaFrame.check()){
            //pulsa
            float totalBelanja = totalHargaPulsa;
            if(cardTxt.equals(cardNum)){
                cardBalance = debitCards.getBalance();
                currBalance = cardBalance;
                float dibayar = cardBalance;
                if (dibayar > totalBelanja){
                    float kembalian = dibayar - totalBelanja;
                    System.out.println(kembalian);
                    kembalianDebitFrame = kembalian;
                    debitCards.updateBalance(kembalian);
                    JOptionPane.showMessageDialog(null, "Pembayaran Berhasil!", "Success!", JOptionPane.INFORMATION_MESSAGE);
                    pulsaFrame.uploadToDB();
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Balance anda tidak cukup!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            } 
        }
        else if(tesframe.check()){
            //barang
            float totalBelanja = totalHargaBarang;
            if(cardTxt.equals(cardNum)){
                cardBalance = debitCards.getBalance();
                float dibayar = cardBalance;
                if (dibayar > totalBelanja){
                    float kembalian = dibayar - totalBelanja;
                    kembalianDebitFrame = kembalian;
                    System.out.println(kembalian);
                    debitCards.updateBalance(kembalian);
                    JOptionPane.showMessageDialog(null, "Pembayaran Berhasil!", "Success!", JOptionPane.INFORMATION_MESSAGE);
                    tesframe.uploadToDB();
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Balance anda tidak cukup!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        else if(tokenFrame.check()){
            //token
            float totalBelanja = totalHargaToken;
            if(cardTxt.equals(cardNum)){
                cardBalance = debitCards.getBalance();
                currBalance = cardBalance;
                float dibayar = cardBalance;
                if (dibayar > totalBelanja){
                    float kembalian = dibayar - totalBelanja;
                    System.out.println(kembalian);
                    kembalianDebitFrame = kembalian;
                    debitCards.updateBalance(kembalian);
                    String Token = tokenFrame.tokenGenerator(20);
                    String formattedToken = tokenFrame.TokenFormatter(Token);
                    JOptionPane.showMessageDialog(null, "Pembayaran Berhasil!\nToken: "+formattedToken, "Success!", JOptionPane.INFORMATION_MESSAGE);
                    tokenFrame.uploadToDB();
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Balance anda tidak cukup!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_submitBTNActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //reset totalHargaPulsa, finalTotalBelanja, dan totalHargaToken menjadi 0 ketika window ini di tutup
        totalHargaPulsa = 0;
        totalHargaBarang = 0;
        totalHargaToken = 0;
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(debitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(debitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(debitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(debitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new debitFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomorDebit;
    private javax.swing.JButton submitBTN;
    // End of variables declaration//GEN-END:variables
}
