/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.application;

import java.time.LocalDateTime;

/**
 *
 * @author chris
 */
public class qrisFrame extends javax.swing.JFrame {

    //konten untuk generate qris, disini konten akan digenerate dari IDPembayaran
    String konten;
    LocalDateTime requestDate;
    String invoiceID;
    String mID = "";
    
    tesframe itemframe = new tesframe();
    tokenFrame tokenframe = new tokenFrame();
    pulsaFrame pulsaframe = new pulsaFrame();
    
    float totalHargaPulsa = pulsaframe.getTotalHarga();
    float totalHargaBarang = itemframe.getTotalHarga();
    float totalHargaToken = tokenframe.getTotalHarga();
    
    static float kembalianQRISFrame;
    
    //qrisFrame yang dibuka dari pulsa
    private static boolean qrisFramePulsaCheck = false;
    
    //qrisFrame yang dibuka dari token
    private static boolean qrisFrameTokenCheck = false;
    
    //qrisFrame yang dibuka dari tesframe(item)
    private static boolean qrisFrameItemCheck = false;
    
    //imaginary balance
    static float balance = 2000000.0f;
    
    /**
     * Creates new form qrisFrame
     */
    public qrisFrame() {
        initComponents();
        
       //check dari mana qrisFrame dibuka
        while(true){
            if(pulsaFrame.check()){         
                System.out.println("pulsa");
                qrisFramePulsaCheck = true;
                konten = String.valueOf(pulsaframe.getIDPembayaran());
                requestDate = pulsaframe.getWaktuPembayaran();
                invoiceID = String.valueOf(pulsaframe.getIDPembayaran());
                break;
            }
            else if(tesframe.check()){     
                System.out.println("barang");
                qrisFrameItemCheck = true;
                konten = String.valueOf(itemframe.getIDPembayaran());
                requestDate = itemframe.getWaktuPembayaran();
                invoiceID = String.valueOf(itemframe.getIDPembayaran());
                break;
            }
            else if(tokenFrame.check()){      
                System.out.println("token");
                qrisFrameTokenCheck = true;
                konten = String.valueOf(tokenframe.getIDPembayaran());
                requestDate = tokenframe.getWaktuPembayaran();
                invoiceID = String.valueOf(tokenframe.getIDPembayaran());
                break;
            }
        }     
    }
    
    private String getKonten(){
        return konten;
    }
    
    private LocalDateTime getTime(){
        return requestDate;
    }
    
    private String getInvoiceID(){
        return invoiceID;
    }
    
    public static float getKembalianQRISFrame(){
        return kembalianQRISFrame;
    }
    
    public static boolean qrisFramePulsaisActive(){
        return qrisFramePulsaCheck;
    }
    
    public static boolean qrisFrameTokenisActive(){
        return qrisFrameTokenCheck;
    }
    
    public static boolean qrisFrameItemisActive(){
        return qrisFrameItemCheck;
    }
    
    public static float getImaginaryBalance(){
        return balance;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(26, 69, 224));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/application/115 asparagus.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/application/117 qrisdummy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        String time = String.valueOf(getTime());

        if(pulsaFrame.check()){
            //pulsa
            float totalBelanja = totalHargaPulsa;
            float kembalian = balance - totalBelanja;    
            kembalianQRISFrame = kembalian;
            pulsaFrame.uploadToDB();
        }
        else if(tesframe.check()){
            //barang
            float totalBelanja = totalHargaBarang;
            float kembalian = balance - totalBelanja;
            kembalianQRISFrame = kembalian;
            tesframe.uploadToDB();
            
        }
        else if(tokenFrame.check()){
            //token
            float totalBelanja = totalHargaToken;
            float kembalian = balance - totalBelanja;       
            kembalianQRISFrame = kembalian;
            tokenFrame.uploadToDB();
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qrisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qrisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qrisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qrisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new qrisFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
